sudo: required

language: python
python:
  - "3.5"

services:
  - docker

install:
  - docker build -t prcleary/weasyprint:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push prcleary/weasyprint:latest
  - docker run -d -p 5001:5001 --name weasyprint prcleary/weasyprint:latest

script:
  - docker ps | grep weasyprint
  - sleep 1
  - docker logs weasyprint
  - curl http://127.0.0.1:5001/health
  - python test.py
  - docker logs weasyprint
